const apiContainer = {
  department: "/department",
  designation: "/designation",
  state: "/state",
  district: "/district",
  country: "/country",
  category: "/category",
  subCategory: "/sub-category",
  applicantType: "/applicant-type",
  disbursedMethod: "/disbursed-method",
  expensiveType: "/expensive-type",
  incomeType: "/income-type",
  addressType: "/address-type",
  proofType: "/proof-type",
  bankAccount: "/bank-account",
  loanChargesDetails: "/loan-charges-details",
  loanChargesType: "/loan-charges-type",
  expenseEntry: "/expense-entry",
  incomeEntry: "/income-entry",
  applicant: "/applicant",
  role: "/role",
  // addLoan: "/loan-details",
  addLoan: "/loan",
  employee: "/employee",
  applicantInfo: "/applicant-info",
  duePayment: "/due-payment",
  applicantAddress: "/applicant-address",
  applicantProof: "/applicant-proof",
};

export default apiContainer;
